/** Channel names for the preload bridge. Keep every string in one place. */
export const IpcChannel = {
  // renderer → main (invoke)
  configLoad: 'config:load',
  configSaveHost: 'config:save-host',
  configDeleteHost: 'config:delete-host',
  configSaveFolder: 'config:save-folder',
  configDeleteFolder: 'config:delete-folder',
  configSaveCredential: 'config:save-credential',
  configDeleteCredential: 'config:delete-credential',
  configSaveSettings: 'config:save-settings',
  configChooseLogDirectory: 'config:choose-log-directory',
  configRevealSecret: 'config:reveal-secret',
  lockStatus: 'lock:status',
  lockUnlock: 'lock:unlock',
  lockSet: 'lock:set',
  lockReset: 'lock:reset',
  revealPath: 'shell:reveal-path',
  clipboardRead: 'clipboard:read',
  clipboardWrite: 'clipboard:write',
  logsListFolders: 'logs:list-folders',
  logsListSessions: 'logs:list-sessions',
  logsOpen: 'logs:open',
  logsLines: 'logs:lines',
  logsSearch: 'logs:search',
  logsClose: 'logs:close',
  logsDeleteSession: 'logs:delete-session',
  logsDeleteFolder: 'logs:delete-folder',
  sessionOpenHost: 'session:open-host',
  sessionOpenSsh: 'session:open-ssh',
  sessionOpenTelnet: 'session:open-telnet',
  sessionOpenSerial: 'session:open-serial',
  sessionReconnect: 'session:reconnect',
  sessionSendBreak: 'session:send-break',
  sessionSetLogging: 'session:set-logging',
  serialList: 'serial:list',
  transferRemoteHome: 'transfer:remote-home',
  transferRemoteList: 'transfer:remote-list',
  transferLocalList: 'transfer:local-list',
  transferDownload: 'transfer:download',
  transferUpload: 'transfer:upload',
  transferChooseDirectory: 'transfer:choose-directory',
  transferConnect: 'transfer:connect',
  transferConnections: 'transfer:connections',
  transferDisconnect: 'transfer:disconnect',
  transferProgress: 'transfer:progress',
  exportConfig: 'transfer:export-config',
  exportBundle: 'transfer:export-bundle',
  importPreview: 'transfer:import-preview',
  importApply: 'transfer:import-apply',
  sessionWrite: 'session:write',
  sessionResize: 'session:resize',
  sessionClose: 'session:close',
  hostKeyRespond: 'host-key:respond',
  authRespond: 'auth:respond',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowClose: 'window:close',
  platformInfo: 'platform:info',

  // main → renderer (send)
  sessionData: 'session:data',
  sessionStatus: 'session:status',
  sessionNotice: 'session:notice',
  sessionLog: 'session:log',
  hostKeyPrompt: 'host-key:prompt',
  authPrompt: 'auth:prompt',
} as const;

export type IpcChannelName = (typeof IpcChannel)[keyof typeof IpcChannel];
