/** Channel names for the preload bridge. Keep every string in one place. */
export const IpcChannel = {
  // renderer → main (invoke)
  configLoad: 'config:load',
  configSaveHost: 'config:save-host',
  configDeleteHost: 'config:delete-host',
  configSaveFolder: 'config:save-folder',
  configDeleteFolder: 'config:delete-folder',
  configSaveCredential: 'config:save-credential',
  configDeleteCredential: 'config:delete-credential',
  configSaveSettings: 'config:save-settings',
  configChooseLogDirectory: 'config:choose-log-directory',
  revealPath: 'shell:reveal-path',
  clipboardRead: 'clipboard:read',
  clipboardWrite: 'clipboard:write',
  logsListFolders: 'logs:list-folders',
  logsListSessions: 'logs:list-sessions',
  logsOpen: 'logs:open',
  logsLines: 'logs:lines',
  logsSearch: 'logs:search',
  logsClose: 'logs:close',
  sessionOpenHost: 'session:open-host',
  sessionOpenSsh: 'session:open-ssh',
  sessionOpenTelnet: 'session:open-telnet',
  sessionOpenSerial: 'session:open-serial',
  sessionSendBreak: 'session:send-break',
  serialList: 'serial:list',
  sessionWrite: 'session:write',
  sessionResize: 'session:resize',
  sessionClose: 'session:close',
  hostKeyRespond: 'host-key:respond',
  authRespond: 'auth:respond',
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowClose: 'window:close',
  platformInfo: 'platform:info',

  // main → renderer (send)
  sessionData: 'session:data',
  sessionStatus: 'session:status',
  sessionNotice: 'session:notice',
  sessionLog: 'session:log',
  hostKeyPrompt: 'host-key:prompt',
  authPrompt: 'auth:prompt',
} as const;

export type IpcChannelName = (typeof IpcChannel)[keyof typeof IpcChannel];
